name: LimpiaTuCiudad CI Pipeline

# 1. ¿Cuándo se ejecuta esto?
on:
  push:
    branches: [ "main" ] # Cuando fusionas algo a main
  pull_request:
    branches: [ "main" ] # Cuando creas un PR hacia main

jobs:
  # ==========================================
  # TRABAJO 1: Validar el Frontend
  # ==========================================
  validar-frontend:
    runs-on: ubuntu-latest
    # Le decimos que todos los comandos se ejecuten dentro de la carpeta frontend
    defaults:
      run:
        working-directory: ./frontend 

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json

    - name: Instalar dependencias limpias
      run: npm ci

    - name: Compilar React/Vite (Verificar que no haya errores de sintaxis)
      run: npm run build


  # ==========================================
  # TRABAJO 2: Validar el Backend
  # ==========================================
  validar-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ./backend/package-lock.json

    - name: Instalar dependencias limpias
      run: npm ci

    # Si tuvieras pruebas unitarias configuradas, este sería el momento de correrlas:
    # - name: Correr pruebas
    #   run: npm test